url: http://lecors.com/
baseurl: ''

# Site settings
title: "#thelecors"
email: shared@lecors.com
description: "Danielle and Chris get married or something"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3dbbf0
  secondary: 2f90b9
  secondary-dark: 333


# Build settings
markdown: kramdown
permalink: pretty
